export interface CreatePMEDto {
  user_id: string;
  nomEntreprise: string;
  anneeCreation: number;
  statutLegal: string;
  secteurActivite: string;
  nombreEmployes: number;
  localisation: string;
  telephone: string;
  email: string;
  historiqueBancaire?: string;
  visionStrategique?: string;
  chiffreAffaires: number;
  beneficeNet: number;
  ratioDettes: number;
  tresorerieDisponible: number;
  delaiPaiementClients: number;
  delaiPaiementFournisseurs: number;
  budgetRD: number;
  nbProduitsLances: number;
  enregistrePertes: boolean;
  accesCredit: boolean;
  garantiesFinancieres: boolean;
  rapportFinancier: boolean;
  businessPlan: boolean;
  caClientPrincipal: number;
  crmOuErp: boolean;
  diversification: boolean;
  dependanceMarchesPublics: boolean;
  investissementDigital: boolean;
  detailsDigitaux?: string;
  manuelProcedures: boolean;
  resilience1?: string;
  resilience2?: string;
  resilience3?: string;
  nbEmploisCrees: number;
  pourcentageFemmes: number;
  actionsSociales: boolean;
  detailsActionsSociales?: string;
  respectEnvironnement: boolean;
  certification: boolean;
  oddImpactes: string //[];
  actionsEcologiques: string //[];
  dirigeantNom: string;
  experienceDirigeant: number;
  formationDirigeant: boolean;
  equipeDirection: boolean;
  gouvernance: boolean;
  cartographieCompetences: string //[];
  planSuccession: boolean;
  formationContinue: boolean;
  tauxRotationPersonnel: number;
  programmeBienEtre: boolean;
  detailsBienEtre?: string;
  defisActuels: string //[];
  objectifs12Mois: string //[];
  benchmarking?: string;
  caMoyenSecteur?: number;
  margeMoyenneSecteur?: number;
  autorisationDonnees: boolean;
  nomSignataire: string;
  dateSignature: string;
  autresActionsEcologiques:string
}
